[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Erkan <erkan808987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
ocl = "0.19"
clap = "3.0.0-beta.1"

